name: Run Python Script

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Run manually

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install necessary packages
      run: sudo apt-get update && sudo apt-get install -y \
        google-chrome-stable \
        xvfb \
        python3-pip

    - name: Install Python dependencies
      run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay

    - name: Set up display
      run: Xvfb :99 -ac & export DISPLAY=:99

    - name: Run script
      run: python Run.py

