name: Run Python Script
 
on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Run manually

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r IDs.txt
    
    - name: Check Python version
      run: python --version

    - name: Run script
      run: |
       python3 Run.py
